services:
  - type: web
    name: eventora-server
    runtime: node
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: PORT
        value: 5000
      - key: VITE_API_URL
        value: /api
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
